apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wothive.fullname" . }}
  labels:
    {{- include "wothive.labels" . | nindent 4 }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wothive.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wothive.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: http 
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        volumeMounts:
        - name: configuration
          mountPath: /usr/src/wothive/configuration.json
          subPath: configuration.json
          readOnly: false
      volumes:
        - name: configuration
          configMap:
            name: {{ include "wothive.fullname" . }}
            defaultMode: 256
            optional: false
