apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triplestore.fullname" . }}
  labels:
    {{- include "triplestore.labels" . | nindent 4 }}
spec:
  replicas:  {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "triplestore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "triplestore.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - name: http 
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        